name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DROGON_VERSION: v1.9.9

jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Latest Clang-Format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run Clang-Format
        run: |
          FILES=$(git ls-files '*.cpp' '*.h')
          clang-format -n --Werror --style=file ${FILES} 2>&1 | tee clang-format-report.txt
          if [ -s clang-format-report.txt ]; then
            echo "Clang-Format found issues."
            exit 1
          fi

  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-tidy \
            cmake \
            ninja-build \
            ccache \
            build-essential \
            libsimdjson-dev \
            libjsoncpp-dev \
            libsodium-dev \
            git \
            g++ \
            uuid-dev \
            openssl \
            libssl-dev \
            zlib1g-dev \
            libpq-dev \
            libhiredis-dev \
            libbrotli-dev
          git clone --depth 1 --branch ${DROGON_VERSION} https://github.com/drogonframework/drogon && \
          cd drogon && \
          git submodule update --init && \
          mkdir build && \
          cd build && \
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. && \
          ninja && ninja install

      - name: Cache CMake & ccache
        uses: actions/cache@v3
        with:
          path: |
            build
            ~/.ccache
          key: cmake-cache-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt') }}
          restore-keys: |
            cmake-cache-${{ runner.os }}-

      - name: Configure CMake with Ninja
        run: |
          cmake -B build \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -G Ninja
          ln -sf build/compile_commands.json compile_commands.json

      - name: Run Clang-Tidy
        run: |
          FILES=$(git ls-files '*.cpp' '*.h')
          run-clang-tidy -p build ${FILES} | tee clang-tidy-report.txt
          if grep -q "warning:" clang-tidy-report.txt; then
            echo "Clang-Tidy found issues."
            exit 1
          fi


  upload-reports:
    name: Upload Clang Reports
    runs-on: ubuntu-latest
    needs: [ clang-format, clang-tidy ]
    if: always()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Clang Reports
        uses: actions/upload-artifact@v4
        with:
          name: clang-reports
          path: clang-*-report.txt